<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pending and Overdue Payment Reminders</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        .overdue {
            background-color: #f8d7da; /* Light red background */
        }
    </style>
</head>
<body>

    <h1>Pending and Overdue Payment Reminders</h1>
    <p>Generated by: {{ $treasurer ? $treasurer->name : 'Unknown' }}</p>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Homeowner</th>
                <th>Title</th>
                <th>Amount</th>
                <th>Due Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reminders as $reminder)
                @php
                    $isOverdue = \Carbon\Carbon::parse($reminder->due_date)->isBefore(now());
                @endphp
                <tr class="{{ $isOverdue ? 'overdue' : '' }}">
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $reminder->homeOwner->fname }} {{ $reminder->homeOwner->lname }}</td>
                    <td>{{ $reminder->title }}</td>
                    <td>{{ $reminder->amount }}</td>
                    <td>{{ \Carbon\Carbon::parse($reminder->due_date)->format('F d, Y') }}</td>
                    <td>{{ $isOverdue ? 'Overdue' : 'Pending' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

</body>
</html>
